### ISSUE TITLE
require('bafa.ui').toggle() not an editor command

### ISSUE THREAD

**Issue by arunkhattri** [mistweaverco/bafa.nvim#2]
How to open bafa buffer? some indications would have helped us "less intelligent souls".

**Comment by gorillamoe** [comment]
I hope `:lua require('bafa.ui').toggle()` should do the trick 👍🏾🤞🏾

**Comment by arunkhattri** [comment]
yes, i missed that 'lua' part..Thanks

**Comment by arunkhattri** [comment]
@gorillamoe thanks
